In [247]:
import pandas as pd
# Loading Data in Pandas Data Frames
trainDF=pd.read_csv('train.csv',index_col=0)
testDF=pd.read_csv('test.csv',index_col=0)
# trainDF.location=trainDF.location.apply(lambda x: int(x.split(' ')[1]))
# testDF.location=testDF.location.apply(lambda x: int(x.split(' ')[1]))
# trainDF.describe()
trainDF.head()

location  fault_severity
id                                 
14121  location 118               1
9320    location 91               0
14394  location 152               1
8218   location 931               1
14804  location 120               0

In [248]:
#merge test and train
data=pd.concat([trainDF,testDF],axis=0)
data.head()

fault_severity      location
id                                 
14121               1  location 118
9320                0   location 91
14394               1  location 152
8218                1  location 931
14804               0  location 120

In [249]:
data.shape

(18552, 2)

In [250]:
eventTypeDF=pd.read_csv('event_type.csv',index_col=0)
logFeatureDF=pd.read_csv('log_feature.csv',index_col=0)
resourceTypeDF=pd.read_csv('resource_type.csv',index_col=0)
severityTypeDF=pd.read_csv('severity_type.csv',index_col=0)

In [251]:
eventTypeVect=pd.get_dummies(eventTypeDF).groupby(eventTypeDF.index).sum()
logFeatureVect=pd.get_dummies(logFeatureDF).groupby(logFeatureDF.index).sum()
resourceTypeVect=pd.get_dummies(resourceTypeDF).groupby(resourceTypeDF.index).sum()
severityTypeVect=pd.get_dummies(severityTypeDF).groupby(severityTypeDF.index).sum()

In [252]:
trainDF=trainDF.join(eventTypeVect).join(logFeatureVect).join(resourceTypeVect).join(severityTypeVect)

In [253]:
trainDF.head()

location  fault_severity  event_type_event_type 1  \
id                                                             
14121  location 118               1                        0   
9320    location 91               0                        0   
14394  location 152               1                        0   
8218   location 931               1                        0   
14804  location 120               0                        0   

       event_type_event_type 10  event_type_event_type 11  \
id                                                          
14121                         0                         0   
9320                          0                         0   
14394                         0                         0   
8218                          0                         1   
14804                         0                         1   

       event_type_event_type 12  event_type_event_type 13  \
id                                                          
14121                         0                         0   
9320                          0                         0   
14394                         0                         0   
8218                          0                         0   
14804                         0                         0   

       event_type_event_type 14  event_type_event_type 15  \
id                                                          
14121                         0                         0   
9320                          0                         0   
14394                         0                         0   
8218                          0                         1   
14804                         0                         0   

       event_type_event_type 17              ...                \
id                                           ...                 
14121                         0              ...                 
9320                          0              ...                 
14394                         0              ...                 
8218                          0              ...                 
14804                         0              ...                 

       resource_type_resource_type 5  resource_type_resource_type 6  \
id                                                                    
14121                              0                              0   
9320                               0                              0   
14394                              0                              0   
8218                               0                              0   
14804                              0                              0   

       resource_type_resource_type 7  resource_type_resource_type 8  \
id                                                                    
14121                              0                              0   
9320                               0                              0   
14394                              0                              0   
8218                               0                              1   
14804                              0                              1   

       resource_type_resource_type 9  severity_type_severity_type 1  \
id                                                                    
14121                              0                              0   
9320                               0                              0   
14394                              0                              0   
8218                               0                              1   
14804                              0                              1   

       severity_type_severity_type 2  severity_type_severity_type 3  \
id                                                                    
14121                              1                              0   
9320                               1                              0   
14394                              1 

In [254]:
#prepare test data
testDF=testDF.join(eventTypeVect).join(logFeatureVect).join(resourceTypeVect).join(severityTypeVect)
testDF.head()

location  event_type_event_type 1  event_type_event_type 10  \
id                                                                       
11066  location 481                        0                         0   
18000  location 962                        0                         0   
16964  location 491                        0                         0   
4795   location 532                        0                         1   
3392   location 600                        0                         0   

       event_type_event_type 11  event_type_event_type 12  \
id                                                          
11066                         0                         0   
18000                         1                         0   
16964                         0                         0   
4795                          0                         0   
3392                          0                         0   

       event_type_event_type 13  event_type_event_type 14  \
id                                                          
11066                         0                         0   
18000                         0                         0   
16964                         0                         0   
4795                          0                         0   
3392                          0                         0   

       event_type_event_type 15  event_type_event_type 17  \
id                                                          
11066                         0                         0   
18000                         1                         0   
16964                         0                         0   
4795                          0                         0   
3392                          1                         0   

       event_type_event_type 18              ...                \
id                                           ...                 
11066                         0              ...                 
18000                         0              ...                 
16964                         0              ...                 
4795                          0              ...                 
3392                          0              ...                 

       resource_type_resource_type 5  resource_type_resource_type 6  \
id                                                                    
11066                              0                              0   
18000                              0                              0   
16964                              0                              0   
4795                               0                              0   
3392                               0                              0   

       resource_type_resource_type 7  resource_type_resource_type 8  \
id                                                                    
11066                              0                              0   
18000                              0                              1   
16964                              0                              0   
4795                               0                              0   
3392                               0                              1   

       resource_type_resource_type 9  severity_type_severity_type 1  \
id                                                                    
11066                              0                              0   
18000                              0                              1   
16964                              0                              0   
4795                               1                              0   
3392                               0                              0   

       severity_type_severity_type 2  severity_type_severity_type 3  \
id                                                                    
11066                              1                              0   
18000                              0  

In [255]:
trainDF.volume.describe()

count    7381.000000
mean       31.820214
std        78.927572
min         1.000000
25%         3.000000
50%         8.000000
75%        25.000000
max      1649.000000
Name: volume, dtype: float64

In [256]:
trainDF.volume.head()

id
14121     38
9320     316
14394      2
8218      22
14804     12
Name: volume, dtype: int64

In [257]:
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline
# trainDF['volume']=trainDF.volume.apply(np.log)
# testDF['volume']=testDF.volume.apply(np.log)
# trainDF.volume.hist()


In [258]:
X=trainDF
X=X.drop(['volume','location','fault_severity'],axis=1)
X=X.as_matrix()
Y=trainDF.fault_severity
Y=Y.as_matrix()

In [259]:
X_test=testDF
X_test=X_test.drop(['volume','location'],axis=1)
X_test=X_test.as_matrix()

In [260]:
from sklearn import metrics
from sklearn import cross_validation
from sklearn.multiclass import OneVsRestClassifier
from sklearn.tree import DecisionTreeClassifier, export_graphviz
from sklearn.naive_bayes import MultinomialNB,BernoulliNB,GaussianNB
from sklearn.cross_validation import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier

In [261]:
clf = MultinomialNB()
# clf=DecisionTreeClassifier(criterion="entropy")
print "training classifier ..."
clf.fit(X,Y)

training classifier ...


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [262]:
print "performing cross fold validation ..."
predicted = cross_validation.cross_val_predict(clf, X, Y, cv=5)

performing cross fold validation ...


In [243]:
print "accuracy score: ", metrics.accuracy_score(Y, predicted)
print "precision score: ", metrics.precision_score(Y, predicted,average='weighted')
print "recall score: ", metrics.recall_score(Y, predicted,average='weighted')

accuracy score:  0.606150928059
precision score:  0.694727648035
recall score:  0.606150928059


In [244]:
print "classification_report: \n ", metrics.classification_report(Y, predicted)

classification_report: 
               precision    recall  f1-score   support

          0       0.85      0.65      0.74      4784
          1       0.44      0.41      0.43      1871
          2       0.30      0.82      0.44       726

avg / total       0.69      0.61      0.63      7381



In [263]:
print "confusion_matrix:\n ", metrics.confusion_matrix(Y,predicted)

confusion_matrix:
  [[3102  885  797]
 [ 527  780  564]
 [   9  124  593]]


In [264]:
# X_test.shape
Y_test=clf.predict_proba(X_test)

In [265]:
# create submission
submission = pd.DataFrame(Y_test,columns=['predict_0','predict_1','predict_2'])
submission.head()
submission['id']=testDF.index.values
cols=submission.columns.tolist()
cols=cols[-1:] + cols[:-1]
submission=submission[cols]
submission.to_csv(open('submission.csv','wt'),index=False)

In [266]:
submission.head()

id  predict_0  predict_1     predict_2
0  11066   0.999796   0.000204  1.106894e-12
1  18000   0.004178   0.059570  9.362523e-01
2  16964   0.999386   0.000614  6.955831e-11
3   4795   0.006220   0.986749  7.031309e-03
4   3392   0.019320   0.091621  8.890588e-01